### PR TITLE
updating, reducing dependencies

### PR DESCRIPTION
**Pull request by trevorhreed**
The version of lodash being used in the published version of the `multi-glob` npm package has a serious security vulnerability. This pull request updates that dependency. In addition, instead of requiring the entire lodash library, this update requires only those portions of lodash that are necessary.

### CODE REVIEW

**Comment by mroderick** [comment]
Did you try running the tests locally?

I think there needs to be a bit of maintenance done to the repository, before this can be made to pass. Would you be up for doing that also?

**Comment by mroderick** [comment]
A bit of background, the [main project under this GitHub organisation: buster](https://github.com/busterjs/buster) has been discontinued. Some repositories have been moved to the `sinonjs` organisation (formatio, referee, samsam), where work continues.

However, none of the `sinonjs` projects use `multi-glob`, so I'd be hesitant in adopting that one into `sinonjs`, or continue to do maintenance on it. 

Would love to hear from some of the other @busterjs/owners, perhaps @dominykas has an opinion on whether or not to continue maintenance on the `busterjs` repositories.

Do you use `multi-glob` directly yourself, or is it used in one of your dependencies?

> What's the minimum version of node that you would like to continue supporting?

Just the [LTS versions](https://github.com/nodejs/Release), so that would be 6 (until April 2019)

**Comment by jodal** [comment]
According to https://www.npmjs.com/package/multi-glob?activeTab=dependents this project has 50 dependents.

**Comment by trevorhreed** [comment]
I have recently found a suitable alternative ([`globs`](https://www.npmjs.com/package/globs)). However, since this package still has quite a bit of usage, I thought I could at least try to help get the lodash dependency updated. Perhaps it would be best to deprecate in favor of `globs`?

**Comment by mroderick** [comment]
Perhaps @stephenmathieson or @thomas-darling could comment on whether or not they are planning to maintain `globs`. It would be silly to deprecate this module in favour of another module that is then deprecated.

**Comment by stephenmathieson** [comment]
I do not have intentions of maintaining the `globs` package, and handed ownership over to @thomas-darling.

**Comment by Natim** [comment]
Apparently the travis config needs to be updated as well.

**Comment by dominykas** [comment]
> According to https://www.npmjs.com/package/multi-glob?activeTab=dependents this project has 50 public dependents.

But it also has only 18k weekly downloads and it hasn't been updated in 3 years and most of the packages that depend on this have also not been updated in over a year, so I wonder if this should just be marked as deprecated?

And the updates that it had also have not changed the main file - which is now 6 years old... The code itself is less than 50 lines of code - easy enough to fork and publish, whereas maintaining this would mean upgrading the node versions, changing the test framework and doing quite some cleanup.

I'm not sure it's worth it. At the same time, given last month's fun with event-stream, I'm not sure that handing over to a new maintainer is best practice either, so I'm saying that someone should fork this, if they want to, and we can add a link to the new package and alternatives in the readme and the deprecation notice?

**Comment by dominykas** [comment]
In fact, I think all of busterjs organization should be marked as archived, and all its packages should be marked as deprecated. @mroderick what do you think? I can probably find time for that this year. It's been a good run - it's time to retire, there's plenty of alternatives.

**Comment by augustl** [comment]
I don't disagree fwiw! We started Buster when the only alternatives were QUnit and jsTestDriver, but there are plenty of great options out there nowadays. And a valuable lesson of shipping sooner and building iterative traction, rather than spending time on perfecting stuff and not releasing it, was learned by yours truly :)

**Comment by cjohansen** [comment]
I agree that archiving these repos would be the right thing to do given that they are truly abandoned (except for the modules expertly curated by the sinonjs crew under @mroderick's leadership).

Still, I think removing a module that have 50 dependents and "just" 18k weekly downloads is a bad idea. Our industry suffers way too much breakage already, let's not contribute to the bonfire. I made a pass at fixing the issues raised in this PR over here: #11 If someone with the keys to the castle could be bothered to bump the version to `1.0.2` and release to npm, then 👍

**Comment by dominykas** [comment]
Just to make sure - I wasn't suggesting removal, only adding a deprecation notice that this is no longer maintained.

I have to 🙇 down to @cjohansen for taking the time to do a cleanup PR, though - I'll merge and publish.

**Comment by mroderick** [comment]
We can move it into the @sinonjs organisation, it has several orphaned projects already.

**Comment by cjohansen** [comment]
Awesome @mroderick! Even though it isn't "actively maintained" - it really is done, and now it has running tests. No point in keep poking at it. If people use it, let 'em.

**Comment by mroderick** [comment]
> @mroderick shall I add you as an owner on npm?

yes please

**Comment by mroderick** [comment]
We should probably also transfer `bane`, as it is used by `@sinonjs/referee` (which we're actively working on)

**Comment by mroderick** [comment]
Perhaps we can get a couple of maintainers to go with the new packages? ;)

**Comment by cjohansen** [comment]
Rather than dragging `bane` along, couldn't `referee` just use `EventEmitter`?

**Comment by mroderick** [comment]
> Rather than dragging `bane` along, couldn't `referee` just use `EventEmitter`?

We're still trying to keep `referee` in a state where it can run as-is in browsers, down to IE11.

**Comment by mroderick** [comment]
In any case, I think it would be a good idea to start marking the unmaintained repositories under `busterjs/` as such and archive them. I am happy to take on `multi-glob`, we can even just put it in it's own organisation.

**Comment by dominykas** [comment]
@mroderick added you on `bane` and `multi-glob` in npm.

We don't strictly need to transfer `bane` or `multi-glob` until a good home comes along?

I'll go through the remaining repos and archive them on GH and deprecate on npm at some point later.

**Pull request closed without merging**
