### PR TITLE
Bring tests back to life and reduce dependencies

### PR DESCRIPTION
**Pull request by cjohansen**
This should achieve the same goal as #9 more thoroughly while also addressing the issues raised there.

### CODE REVIEW

**Comment by cjohansen** [comment]
👍 Thanks @dominykas

**Comment by mroderick** [comment]
Whoop!

**Comment by dominykas** [comment]
Published `+ multi-glob@1.0.2`

**Comment by Natim** [comment]
Thank you for your collaboration.

**Pull request merged**
